### ISSUE TITLE
Will it have TypeScript support?

### ISSUE THREAD

**Issue by kaname-png** [Butterstroke/AniList-Node#13]
I want to use this package with my TypeScript project but I am not shown any method as it should be in TypeScript.

**Comment by Butterstroke** [comment]
@taksumaki Sorry I didn't see this earlier. The notifications didn't get through and I just saw this now.

TypeScript support would be nice to have but it's not on my radar at the moment. I will have look into it after I finish the updates I have planned. Though, you are more than welcome to add your own TypeScript support for it in the meantime.
