### ISSUE TITLE
Activity of users

### ISSUE THREAD

**Issue by Subtilizer28** [Butterstroke/AniList-Node#14]
Does this have like a command to view your friends Activity. Like what that person watched/read today.

**Comment by Butterstroke** [comment]
Unfortunately, you can't pull user activity at the moment. But, I'll mark this as a todo so it can get implemented.

**Comment by Butterstroke** [comment]
Hello,

I figure I let you know that this is now possible via the getRecentActivity method with v1.6.0.  

As such, I'll be closing this issue now. Hopefully, this is what you were looking for. If not, feel free to make another issue or make your own changes and submit a pull request.
