### ISSUE TITLE
AniList responses don't always include "Page" property which causes some requests to fail

### ISSUE THREAD

**Issue by VeikkoLehmuskorpi** [Butterstroke/AniList-Node#16]
For example, trying to fetch someone's anime lists
```js
const lists = await Anilist.lists.anime(USERNAME);
```

```
(node:10625) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'activities' of undefined
    at Utilities.send (/.../node_modules/anilist-node/lib/fetcher.js:127:28)
```

https://github.com/Butterstroke/AniList-Node/blob/master/lib/fetcher.js#L127-L129

---

An easy fix would be to check if the Page property is defined before trying to access the deeper properties
```js
if (json.data.Page && json.data.Page.activities) { ... }
```

**Comment by Butterstroke** [comment]
Thanks for the detailed report! I'll add these changes right away and you should be seeing a bug patch for this out soon.

**Comment by Butterstroke** [comment]
And the patch is out! You should be able to see the update either here on GitHub or on NPM. Thanks again for the report.
