### ISSUE TITLE
Can't use args[...] in place of the Anilist ID

### ISSUE THREAD

**Issue by Fukur0u** [Butterstroke/AniList-Node#21]
**Description**
Use of arguments is currently not possible with default code.

**Steps to Reproduce**
1. Load the module into your project
2. Attempt to use the example code like this
```
const anilist = require('anilist-node');
const Anilist = new anilist();

Anilist.media.anime(**args[0]**).then(data => {
    console.log(data);
});
```
3. Receive the "Term provided is not a number!" error

**Environment**
Node.js Version: 14.15.4
AniList-Node Version: 1.7.0

**Screenshots**

**Additional context**
Commented out line 25 in this file
[https://github.com/Butterstroke/AniList-Node/blob/master/lib/media.js](url)
Arguments were able to pass through, and the correct data was grabbed.

While the addition of this line helps make sure the correct string is passed, it checks the code before the actual argument and kills the process. Might want to add some exception for `args[...]`

**Comment by Butterstroke** [comment]
Do you know what you were passing within the args? While I think adding another exception is a good idea, I don't want to blindly add in an array check and hope the arguments within it are fine.

**Comment by Fukur0u** [comment]
> Do you know what you were passing within the args? While I think adding another exception is a good idea, I don't want to blindly add in an array check and hope the arguments within it are fine.

Thats true also.
The args I passed were always the anime ID. It would work if you directly put the ID into the code, and then wouldn't when you put args[...] in the code, and tried to pass an ID.
Just wanted to bring attention to it. I'm really knowledgeable enough to give code advice so up to your discretion whether you leave it as is or not.

**Comment by Butterstroke** [comment]
> The args I passed were always the anime ID. It would work if you directly put the ID into the code, and then wouldn't when you put args[...] in the code, and tried to pass an ID.

...Wait a moment. Just to make sure I read this right. Are you passing an item within an array, not the array itself, and it is failing? I might have misread this initially thinking it was the whole array. If it is just an item within an array, check to make sure the item is a number type and not a string. You might have to convert it into a number beforehand then.

> Just wanted to bring attention to it. I'm not really knowledgeable enough to give code advice so up to your discretion whether you leave it as is or not.

That's fine. I don't mind the advice. I would not have made this public if I didn't want to hear from others about code. 😄

**Comment by Fukur0u** [comment]
> ...Wait a moment. Just to make sure I read this right. Are you passing an item within an array, not the array itself, and it is failing? I might have misread this initially thinking it was the whole array. If it is just an item within an array, check to make sure the item is a number type and not a string. You might have to convert it into a number beforehand then.

Not from an array. Just a random value that the user defines, which, elsewhere in my version of the code, is required to be a string of numbers. For example, args[0], which is what I have in my code right now, just passes the first string of numbers that the user specifies to the function.

`Anilist.media.anime(args[0])`

**Comment by Butterstroke** [comment]
> Not from an array. Just a random value that the user defines, which, elsewhere in my version of the code, is required to be a string of numbers. For example, args[0], which is what I have in my code right now, just passes the first string of numbers that the user specifies to the function.
> 
> `Anilist.media.anime(args[0])`

Ah, I get it now. I was misreading this. You just have to convert the variable type for `args[0]` into a number and it should work. So something like `Anilist.media.anime(Number(args[0]))` is fine and shouldn't affect the value outside of the anime method.

**Comment by Butterstroke** [comment]
Not hearing anything else on the matter so I'll be closing this issue now.
