### ISSUE TITLE
Mutations

### ISSUE THREAD

**Issue by proohit** [Butterstroke/AniList-Node#34]
Are there any plans on providing Mutation wrappings according to https://anilist.gitbook.io/anilist-apiv2-docs/overview/graphql/mutations ?

**Comment by Butterstroke** [comment]
Yes, there are plans to add that eventually. I can't say when though since I have no idea when I will be able to add it in. That said, it's fair game for anyone to try.

**Comment by proohit** [comment]
I'll see if I can find some free time to dive into it :)

**Comment by Butterstroke** [comment]
Just cleaning up the repo a bit. The package has been supporting mutations for a few months now so no need to keep this ticket open.
