### ISSUE TITLE
Advice for not going over the X-RateLimit-Limit

### ISSUE THREAD

**Issue by kanjieater** [Butterstroke/AniList-Node#35]
As documented [here](https://anilist.gitbook.io/anilist-apiv2-docs/overview/rate-limiting) there is rate limiting in place. While it is fairly generous currently at 90 rpm, I'm not sure if there's any way to use this from the node wrapper. 

Would it be possible to either:
1. Expose the useful headers from the library:
```
Retry-After: 30
X-RateLimit-Limit: 90
X-RateLimit-Remaining: 0
X-RateLimit-Reset: 1502035959
```
2. Automatically handle it inside the library, by holding off on sending/resolving the promise response until the call has been made without exceeding the rate limit.

Would this be in scope for the library or do you have any advice for not exceeding the rate limit? Thanks!

**Comment by Butterstroke** [comment]
There is nothing in the library to help with rate limits right now. Currently if you do come across a rate limit response in your queries with the library, you should get the error message response that the API sends. 

That said, handling the rate limits would certainly be in scope depending on how it's handled. 

> 1. Expose the useful headers from the library

Currently, the response data is put into a JSON format and then send to the user. So if there is headers in the response, it would have to be taken from the raw response data. That said, I don't know if node-fetch (the library used to make the web requests) provides the headers in responses as AniList-Node has always converted it to JSON before formatting. So exposing it could mean figuring out how to add them and then send it in the JSON object.

> 2. Automatically handle it inside the library, by holding off on sending/resolving the promise response until the call has been made without exceeding the rate limit.

I think I would prefer this method over exposing the headers if rate handling was to exist in the library. But my only idea for it right now is to make a system that creates 90 timers to track the rate limit. Which is really inefficient... would definitely need some more thought if it was being developed.

> do you have any advice for not exceeding the rate limit

Right now, for a lot of the more advanced stuff that's not in the library, I refer users to the AniList API and their documentation. Same applies to the rate limits in a sense where the information is provided and users can create their own external systems to manage their limits. Personally, for public programs, I limit the amount of attempts which users could even attempt to hit the API and therefore stay under the limit.

**Comment by Butterstroke** [comment]
Not hearing any other comments, I'll be closing this issue.
