### ISSUE TITLE
How can I search anime characters 

### ISSUE THREAD

**Issue by Debanjan-San** [Butterstroke/AniList-Node#67]

**Comment by Butterstroke** [comment]
Hello,

You can use the method `AniList.searchEntry.character` to search for anime characters by names. You can find more information about it and what it returns in the documentation here: https://katsurin.com/docs/anilist-node/AniList.Search.html#character

**Comment by Butterstroke** [comment]
It's been a couple of days since I commented on this. I'll be considering this ticket as solved at this point.
