### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by sech1p** [Butterstroke/AniList-Node#72]
**Description**
I'm trying to make a discord bot with AniList API. However, when i'm trying to execute command of find e.g. user (this problem are occured on anime and manga too) it's returns a Bad Request HTTP error

**Environment**
Node.js Version: 20.9.0
AniList-Node Version: 1.14.0

**Screenshots**
![image](https://github.com/Butterstroke/AniList-Node/assets/19610068/afaeb98e-68e7-4412-8f70-ad9c290ed0e4)
![image](https://github.com/Butterstroke/AniList-Node/assets/19610068/34f43555-60d0-47d3-8451-4b821b696303)

**Comment by Butterstroke** [comment]
Hello!

Do you know what values you are searching with? I am assuming this is the same issue for all three of your commands. However, my testing with user search right now, everything seems to be in working condition.

![image](https://github.com/Butterstroke/AniList-Node/assets/26350892/1fbd2f13-5dc0-4421-a27b-e3ea96618285)
![image](https://github.com/Butterstroke/AniList-Node/assets/26350892/faa355d2-622d-467f-a9d8-b44e8412e74d)

![image](https://github.com/Butterstroke/AniList-Node/assets/26350892/17604f3a-93d4-48b4-8366-1a2c68573e47)
![image](https://github.com/Butterstroke/AniList-Node/assets/26350892/4eeaa5f5-014e-43e3-988d-e9d73a4e2bb5)

**Comment by sech1p** [comment]
This issue has been caused by providing argument with AniList key in new object, now it works correctly. Thank you
